[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[colors]

[colors.primary]
background = '#0d1422'
foreground = '#ffffff'

[colors.cursor]
text   = '#0d1422'
cursor = '#ffffff'

# Normal colors
[colors.normal]
black   = '#1a2540'   
red     = '#c87060'   
green   = '#ffffff'
yellow  = '#c8a46a'   
blue    = '#4a72b8'   
magenta = '#7a7ab0'   
cyan    = '#7ab8cc'   
white   = '#c0cedf'   

# Bright colors
[colors.bright]
black   = '#2d3e5c'   
red     = '#e08070'   
green   = '#8ac8b8'   
yellow  = '#e8c07a'   
blue    = '#6a92d8'   
magenta = '#9a9ad0'   
cyan    = '#9acce0'   
white   = '#e8eef8'   

[window]

padding.x = 15
padding.y = 15
opacity = 0.9

decorations = "None"

[font]

normal.family = "JetBrainsMono NF"
size = 11.0

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "ToggleViMode"


